# Site settings
title: Kayden Arias Sharky Althen
description: A personal website and blog
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000"

# User settings
username: sharkySharks
user_description:
user_title: Software Developer
email: kaydenalthen@gmail.com
twitter_username: sharkyAlt
github_username:  sharkySharks
linkedIn_username: kaydenalthen

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
