# Site settings
title: Kayden Arias Sharky Althen
description: A personal website and blog
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000"

username: sharkySharks
user_title: Software Engineer
email: kaydenalthen@gmail.com
twitter_username: sharkyAlt
github_username:  sharkySharks
linkedIn_username: kaydenalthen

# Google-analytics
google-analytics:
  id: "G-LWHXDR8VRE"

exclude: [
  'package.json',
  'src' , 
  'node_modules', 
  'gulpfile.js'
]
